import { v4 as uuid } from "uuid";

import { BookImage } from "../../Utility/BookImage"

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    description: "A classic novel depicting the decadence of the Jazz Age.",
    price: 12.99,
    category: "Fiction",
    coverImage: BookImage[0],
    ratings: 1.5,
    inStock: false,
    publisher: "Scribner",
    publishedYear: 1925,
    pages: 180,
    bestseller: true,
    review: 106
  },
  {
    _id: uuid(),
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    description: "A compelling story dealing with racial injustice and moral growth.",
    price: 10.99,
    category: "Fiction",
    coverImage: BookImage[1],
    ratings: 2.8,
    inStock: true,
    publisher: "HarperCollins",
    publishedYear: 1960,
    pages: 336,
    bestseller: false,
    review: 48
  },
  {
    _id: uuid(),
    title: "1984",
    author: "George Orwell",
    description: "A dystopian novel exploring the dangers of totalitarianism.",
    price: 9.99,
    category: "Science Fiction",
    coverImage: BookImage[2],
    ratings: 3.6,
    inStock: true,
    publisher: "Secker & Warburg",
    publishedYear: 1949,
    pages: 328,
    bestseller: false,
    review: 95
  },
  {
    _id: uuid(),
    title: "Pride and Prejudice",
    author: "Jane Austen",
    description: "A classic novel of love, manners, and misunderstandings in 19th-century England.",
    price: 8.99,
    category: "Romance",
    coverImage: BookImage[3],
    ratings: 4.7,
    inStock: true,
    publisher: "T. Egerton, Whitehall",
    publishedYear: 1813,
    pages: 432,
    bestseller: false,
    review: 465
  },
  {
    _id: uuid(),
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    description: "A fantasy adventure novel set in Middle-earth, preceding The Lord of the Rings.",
    price: 11.49,
    category: "Fantasy",
    coverImage: BookImage[4],
    ratings: 2.9,
    inStock: true,
    publisher: "Allen & Unwin",
    publishedYear: 1937,
    pages: 310,
    bestseller: false,
    review: 892
  },
  {
    _id: uuid(),
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    description: "A novel following the experiences of Holden Caulfield, a disenchanted teenager.",
    price: 9.99,
    category: "Fiction",
    coverImage: BookImage[5],
    ratings: 3.3,
    inStock: true,
    publisher: "Little, Brown and Company",
    publishedYear: 1951,
    pages: 234,
    bestseller: false,
    review: 165
  },
  {
    _id: uuid(),
    title: "The Alchemist",
    author: "Paulo Coelho",
    description: "A philosophical novel about a shepherd named Santiago and his journey to find treasure.",
    price: 14.99,
    category: "Adventure",
    coverImage: BookImage[6],
    ratings: 4.6,
    inStock: false,
    publisher: "HarperOne",
    publishedYear: 1988,
    pages: 208,
    bestseller: true,
    review: 423
  },
  {
    _id: uuid(),
    title: "The Da Vinci Code",
    author: "Dan Brown",
    description: "A thriller centered around a symbologist's quest to unravel hidden mysteries.",
    price: 12.49,
    category: "Thriller",
    coverImage: BookImage[7],
    ratings: 4.2,
    inStock: true,
    publisher: "Doubleday",
    publishedYear: 2003,
    pages: 454,
    bestseller: false,
    review: 83
  },
  {
    _id: uuid(),
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    description: "The first book in the Harry Potter series, introducing the magical world of Hogwarts.",
    price: 10.99,
    category: "Fantasy",
    coverImage: BookImage[8],
    ratings: 1.8,
    inStock: true,
    publisher: "Bloomsbury",
    publishedYear: 1997,
    pages: 309,
    bestseller: true,
    review: 589
  },
  {
    _id: uuid(),
    title: "The Hunger Games",
    author: "Suzanne Collins",
    description: "A dystopian novel set in a post-apocalyptic world where teenagers are forced to fight to the death.",
    price: 9.99,
    category: "Science Fiction",
    coverImage: BookImage[9],
    ratings: 2.5,
    inStock: true,
    publisher: "Scholastic",
    publishedYear: 2008,
    pages: 374,
    bestseller: false,
    review: 753
  },
  {
    _id: uuid(),
    title: "Brave New World",
    author: "Aldous Huxley",
    description: "A futuristic novel exploring a society driven by technological advancements and conformity.",
    price: 11.99,
    category: "Science Fiction",
    coverImage: BookImage[10],
    ratings: 3.1,
    inStock: false,
    publisher: "Chatto & Windus",
    publishedYear: 1932,
    pages: 311,
    bestseller: false,
    review: 951
  },
  {
    _id: uuid(),
    title: "The Lord of the Rings: The Fellowship of the Ring",
    author: "J.R.R. Tolkien",
    description: "The first part of the epic fantasy trilogy set in Middle-earth.",
    price: 13.49,
    category: "Fantasy",
    coverImage: BookImage[11],
    ratings: 4.9,
    inStock: true,
    publisher: "Allen & Unwin",
    publishedYear: 1954,
    pages: 423,
    bestseller: false,
    review: 456
  },
  {
    _id: uuid(),
    title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
    author: "C.S. Lewis",
    description: "A classic fantasy novel about siblings who discover a magical land through a wardrobe.",
    price: 8.99,
    category: "Fantasy",
    coverImage: BookImage[12],
    ratings: 2.7,
    inStock: true,
    publisher: "Geoffrey Bles",
    publishedYear: 1950,
    pages: 206,
    bestseller: true,
    review: 754
  },
  {
    _id: uuid(),
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    description: "A powerful novel set in Afghanistan, exploring friendship, redemption, and the impact of choices.",
    price: 10.49,
    category: "Drama",
    coverImage: BookImage[13],
    ratings: 3.6,
    inStock: true,
    publisher: "Riverhead Books",
    publishedYear: 2003,
    pages: 371,
    bestseller: false,
    review: 159
  },
  {
    _id: uuid(),
    title: "The Shining",
    author: "Stephen King",
    description: "A psychological horror novel about a family's chilling experiences in a haunted hotel.",
    price: 9.99,
    category: "Horror",
    coverImage: BookImage[14],
    ratings: 3.3,
    inStock: false,
    publisher: "Doubleday",
    publishedYear: 1977,
    pages: 447,
    bestseller: false,
    review: 357
  },
  {
    _id: uuid(),
    title: "The Girl on the Train",
    author: "Paula Hawkins",
    description: "A psychological thriller revolving around a woman's observations on her daily train commute.",
    price: 11.99,
    category: "Fiction",
    coverImage: BookImage[15],
    ratings: 4.0,
    inStock: true,
    publisher: "Riverhead Books",
    publishedYear: 2015,
    pages: 336,
    bestseller: false,
    review: 42
  },
  {
    _id: uuid(),
    title: "The Martian",
    author: "Andy Weir",
    description: "An adventure novel about an astronaut's struggle to survive on Mars after being stranded by his crew.",
    price: 10.49,
    category: "Science Fiction",
    coverImage: BookImage[16],
    ratings: 4.7,
    inStock: true,
    publisher: "Crown Publishing Group",
    publishedYear: 2011,
    pages: 369,
    bestseller: true,
    review: 86
  },
  {
    _id: uuid(),
    title: "Gone Girl",
    author: "Gillian Flynn",
    description: "A suspenseful mystery revolving around the mysterious disappearance of a woman and the secrets that unravel.",
    price: 9.99,
    category: "Thriller",
    coverImage: BookImage[17],
    ratings: 4.4,
    inStock: true,
    publisher: "Crown Publishing Group",
    publishedYear: 2012,
    pages: 432,
    bestseller: false,
    review: 57
  },
  {
    _id: uuid(),
    title: "The Fault in Our Stars",
    author: "John Green",
    description: "A heartwarming novel following two teenagers who meet at a cancer support group and fall in love.",
    price: 8.99,
    category: "Fantasy",
    coverImage: BookImage[18],
    ratings: 4.5,
    inStock: true,
    publisher: "Dutton Books",
    publishedYear: 2012,
    pages: 313,
    bestseller: false,
    review: 68
  },
  {
    _id: uuid(),
    title: "The Girl with the Dragon Tattoo",
    author: "Stieg Larsson",
    description: "A mystery novel featuring a journalist and a hacker as they investigate a decades-old disappearance.",
    price: 12.99,
    category: "Thriller",
    coverImage: BookImage[19],
    ratings: 4.2,
    inStock: false,
    publisher: "Norstedts Förlag",
    publishedYear: 2005,
    pages: 672,
    bestseller: false,
    review: 258
  },
  {
    _id: uuid(),
    title: "The Road",
    author: "Cormac McCarthy",
    description: "A post-apocalyptic novel following a father and son's journey to survive in a desolate world.",
    price: 9.49,
    category: "Science Fiction",
    coverImage: BookImage[20],
    ratings: 4.1,
    inStock: true,
    publisher: "Alfred A. Knopf",
    publishedYear: 2006,
    pages: 241,
    bestseller: true,
    review: 369
  }  
];
