import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    description: "A classic novel depicting the decadence of the Jazz Age.",
    price: 12.99,
    category: "Fiction",
    coverImage: "cover1.jpg",
    ratings: 4.5,
    language: "English",
    publisher: "Scribner",
    publishedYear: 1925,
    pages: 180,
    isbn: "978-0-7432-7356-5"
  },
  {
    _id: uuid(),
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    description: "A compelling story dealing with racial injustice and moral growth.",
    price: 10.99,
    category: "Fiction",
    coverImage: "cover2.jpg",
    ratings: 4.8,
    language: "English",
    publisher: "HarperCollins",
    publishedYear: 1960,
    pages: 336,
    isbn: "978-0-06-112008-4"
  },
  {
    _id: uuid(),
    title: "1984",
    author: "George Orwell",
    description: "A dystopian novel exploring the dangers of totalitarianism.",
    price: 9.99,
    category: "Science Fiction",
    coverImage: "cover3.jpg",
    ratings: 4.6,
    language: "English",
    publisher: "Secker & Warburg",
    publishedYear: 1949,
    pages: 328,
    isbn: "978-0-452-28423-4"
  },
  {
    _id: uuid(),
    title: "Pride and Prejudice",
    author: "Jane Austen",
    description: "A classic novel of love, manners, and misunderstandings in 19th-century England.",
    price: 8.99,
    category: "Romance",
    coverImage: "cover21.jpg",
    ratings: 4.7,
    language: "English",
    publisher: "T. Egerton, Whitehall",
    publishedYear: 1813,
    pages: 432,
    isbn: "978-0-14-143951-8"
  },
  {
    _id: uuid(),
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    description: "A fantasy adventure novel set in Middle-earth, preceding The Lord of the Rings.",
    price: 11.49,
    category: "Fantasy",
    coverImage: "cover22.jpg",
    ratings: 4.9,
    language: "English",
    publisher: "Allen & Unwin",
    publishedYear: 1937,
    pages: 310,
    isbn: "978-0-261-10217-3"
  },
  {
    _id: uuid(),
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    description: "A novel following the experiences of Holden Caulfield, a disenchanted teenager.",
    price: 9.99,
    category: "Fiction",
    coverImage: "cover23.jpg",
    ratings: 4.3,
    language: "English",
    publisher: "Little, Brown and Company",
    publishedYear: 1951,
    pages: 234,
    isbn: "978-0-316-76947-6"
  },
  {
    _id: uuid(),
    title: "The Alchemist",
    author: "Paulo Coelho",
    description: "A philosophical novel about a shepherd named Santiago and his journey to find treasure.",
    price: 14.99,
    category: "Adventure",
    coverImage: "cover31.jpg",
    ratings: 4.6,
    language: "English",
    publisher: "HarperOne",
    publishedYear: 1988,
    pages: 208,
    isbn: "978-0-06-112241-5"
  },
  {
    _id: uuid(),
    title: "The Da Vinci Code",
    author: "Dan Brown",
    description: "A thriller centered around a symbologist's quest to unravel hidden mysteries.",
    price: 12.49,
    category: "Thriller",
    coverImage: "cover32.jpg",
    ratings: 4.2,
    language: "English",
    publisher: "Doubleday",
    publishedYear: 2003,
    pages: 454,
    isbn: "978-0-385-50420-8"
  },
  {
    _id: uuid(),
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    description: "The first book in the Harry Potter series, introducing the magical world of Hogwarts.",
    price: 10.99,
    category: "Fantasy",
    coverImage: "cover33.jpg",
    ratings: 4.8,
    language: "English",
    publisher: "Bloomsbury",
    publishedYear: 1997,
    pages: 309,
    isbn: "978-0-7475-3269-6"
  },
  {
    _id: uuid(),
    title: "The Hunger Games",
    author: "Suzanne Collins",
    description: "A dystopian novel set in a post-apocalyptic world where teenagers are forced to fight to the death.",
    price: 9.99,
    category: "Science Fiction",
    coverImage: "cover38.jpg",
    ratings: 4.5,
    language: "English",
    publisher: "Scholastic",
    publishedYear: 2008,
    pages: 374,
    isbn: "978-0-439-02352-8"
  },
  {
    _id: uuid(),
    title: "Brave New World",
    author: "Aldous Huxley",
    description: "A futuristic novel exploring a society driven by technological advancements and conformity.",
    price: 11.99,
    category: "Science Fiction",
    coverImage: "cover39.jpg",
    ratings: 4.1,
    language: "English",
    publisher: "Chatto & Windus",
    publishedYear: 1932,
    pages: 311,
    isbn: "978-0-06-085052-4"
  },
  {
    _id: uuid(),
    title: "The Lord of the Rings: The Fellowship of the Ring",
    author: "J.R.R. Tolkien",
    description: "The first part of the epic fantasy trilogy set in Middle-earth.",
    price: 13.49,
    category: "Fantasy",
    coverImage: "cover40.jpg",
    ratings: 4.9,
    language: "English",
    publisher: "Allen & Unwin",
    publishedYear: 1954,
    pages: 423,
    isbn: "978-0-261-10228-9"
  },
  {
    _id: uuid(),
    title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
    author: "C.S. Lewis",
    description: "A classic fantasy novel about siblings who discover a magical land through a wardrobe.",
    price: 8.99,
    category: "Fantasy",
    coverImage: "cover42.jpg",
    ratings: 4.7,
    language: "English",
    publisher: "Geoffrey Bles",
    publishedYear: 1950,
    pages: 206,
    isbn: "978-0-06-076545-1"
  },
  {
    _id: uuid(),
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    description: "A powerful novel set in Afghanistan, exploring friendship, redemption, and the impact of choices.",
    price: 10.49,
    category: "Drama",
    coverImage: "cover43.jpg",
    ratings: 4.6,
    language: "English",
    publisher: "Riverhead Books",
    publishedYear: 2003,
    pages: 371,
    isbn: "978-1-57322-245-7"
  },
  {
    _id: uuid(),
    title: "The Shining",
    author: "Stephen King",
    description: "A psychological horror novel about a family's chilling experiences in a haunted hotel.",
    price: 9.99,
    category: "Horror",
    coverImage: "cover44.jpg",
    ratings: 4.3,
    language: "English",
    publisher: "Doubleday",
    publishedYear: 1977,
    pages: 447,
    isbn: "978-0-385-12167-5"
  }
];
